import {Arm, Degree, Direction, Kata, Level, Stance, Type} from "./types";

export const taikyokuSonoIchi: Kata = {
    name: 'Taikyoku Sono Ichi',
    steps: [
        {
            stance: Stance.FRONT,
            type: Type.SWIPE,
            limb: Arm.SEIKEN,
            level: Level.LOW,
            direction: Direction.LEFT,
            degree: Degree.NINETY,
        },
        {
            stance: Stance.FRONT,
            type: Type.ATTACK,
            limb: Arm.SEIKEN,
            level: Level.MIDDLE,
            direction: Direction.RIGHT,
            degree: Degree.NINETY,
        },
        {
            stance: Stance.FRONT,
            type: Type.SWIPE,
            limb: Arm.SEIKEN,
            level: Level.LOW,
            direction: Direction.RIGHT,
            degree: Degree.NINETY,
        },
        {
            stance: Stance.FRONT,
            type: Type.ATTACK,
            limb: Arm.SEIKEN,
            level: Level.MIDDLE,
            direction: Direction.LEFT,
            degree: Degree.NINETY,
        },
        {
            stance: Stance.FRONT,
            type: Type.SWIPE,
            limb: Arm.SEIKEN,
            level: Level.LOW,
            direction: Direction.LEFT,
            degree: Degree.NINETY,
        },
        {
            stance: Stance.FRONT,
            type: Type.ATTACK,
            limb: Arm.SEIKEN,
            level: Level.MIDDLE,
            direction: Direction.RIGHT,
        },
        {
            stance: Stance.FRONT,
            type: Type.ATTACK,
            limb: Arm.SEIKEN,
            level: Level.MIDDLE,
            direction: Direction.LEFT,
        },
        {
            stance: Stance.FRONT,
            type: Type.ATTACK,
            limb: Arm.SEIKEN,
            level: Level.MIDDLE,
            direction: Direction.RIGHT,
        },
        {
            stance: Stance.FRONT,
            type: Type.SWIPE,
            limb: Arm.SEIKEN,
            level: Level.LOW,
            direction: Direction.LEFT,
        },
        {
            stance: Stance.FRONT,
            type: Type.ATTACK,
            limb: Arm.SEIKEN,
            level: Level.MIDDLE,
            direction: Direction.RIGHT,
            degree: Degree.NINETY,
        },
        {
            stance: Stance.FRONT,
            type: Type.SWIPE,
            limb: Arm.SEIKEN,
            level: Level.LOW,
            direction: Direction.RIGHT,
            degree: Degree.NINETY
        },
        {
            stance: Stance.FRONT,
            type: Type.ATTACK,
            limb: Arm.SEIKEN,
            level: Level.MIDDLE,
            direction: Direction.LEFT,
            degree: Degree.NINETY,
        },
        {
            stance: Stance.FRONT,
            type: Type.SWIPE,
            limb: Arm.SEIKEN,
            level: Level.LOW,
            direction: Direction.LEFT,
            degree: Degree.NINETY,
        },
        {
            stance: Stance.FRONT,
            type: Type.ATTACK,
            limb: Arm.SEIKEN,
            level: Level.MIDDLE,
            direction: Direction.RIGHT,
            degree: Degree.NINETY,
        },
        {
            stance: Stance.FRONT,
            type: Type.ATTACK,
            limb: Arm.SEIKEN,
            level: Level.MIDDLE,
            direction: Direction.LEFT,
            degree: Degree.NINETY,
        },
        {
            stance: Stance.FRONT,
            type: Type.ATTACK,
            limb: Arm.SEIKEN,
            level: Level.MIDDLE,
            direction: Direction.RIGHT,
            degree: Degree.NINETY,
        },
        {
            stance: Stance.FRONT,
            type: Type.SWIPE,
            limb: Arm.SEIKEN,
            level: Level.LOW,
            direction: Direction.LEFT,
            degree: Degree.NINETY,
        },
        {
            stance: Stance.FRONT,
            type: Type.ATTACK,
            limb: Arm.SEIKEN,
            level: Level.MIDDLE,
            direction: Direction.RIGHT,
            degree: Degree.NINETY,
        },
        {
            stance: Stance.FRONT,
            type: Type.SWIPE,
            limb: Arm.SEIKEN,
            level: Level.LOW,
            direction: Direction.RIGHT,
            degree: Degree.NINETY,
        },
        {
            stance: Stance.FRONT,
            type: Type.ATTACK,
            limb: Arm.SEIKEN,
            level: Level.MIDDLE,
            direction: Direction.LEFT,
            degree: Degree.NINETY,
        }
    ]
}

export const katas = [taikyokuSonoIchi];
